DEBUG 2020-05-12 06:36:37.594 UTC: 	 Running on: Linux ui03.recas.ba.infn.it 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-05-12 06:36:37.605 UTC: 	 OpenSSl version: OpenSSL 1.0.2k-fips  26 Jan 2017 (Library: OpenSSL 1.0.2d-fips 9 Jul 2015)
DEBUG 2020-05-12 06:36:37.606 UTC: 	 Executing command: 'submit'
DEBUG 2020-05-12 06:36:37.606 UTC: 	 Found CRAB cache file /lustre/home/venditti/.crab3
INFO 2020-05-12 06:36:37.607 UTC: 	 Will use CRAB configuration file crab_T3Mu_BPH4_RunA_cfg.py
DEBUG 2020-05-12 06:36:37.607 UTC: 	 Loading CRAB configuration file.
ERROR 2020-05-12 06:36:37.610 UTC: 	 Error while loading CRAB configuration:
cannot import name getUsernameFromSiteDB
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2020-05-12 06:36:37.610 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2004/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2004/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2004/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2004/lib/CRABClient/Commands/SubCommand.py", line 318, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2004/lib/CRABClient/Commands/SubCommand.py", line 88, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Error while loading CRAB configuration:
cannot import name getUsernameFromSiteDB
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
DEBUG 2020-05-12 10:40:34.585 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-05-12 10:40:34.602 UTC: 	 OpenSSl version: OpenSSL 1.0.2k-fips  26 Jan 2017 (Library: OpenSSL 1.0.2d-fips 9 Jul 2015)
DEBUG 2020-05-12 10:40:34.603 UTC: 	 Executing command: 'submit'
DEBUG 2020-05-12 10:40:34.603 UTC: 	 Found CRAB cache file /lustre/home/venditti/.crab3
INFO 2020-05-12 10:40:34.604 UTC: 	 Will use CRAB configuration file crab_T3Mu_BPH4_RunA_cfg.py
DEBUG 2020-05-12 10:40:34.604 UTC: 	 Loading CRAB configuration file.
ERROR 2020-05-12 10:40:34.608 UTC: 	 Error while loading CRAB configuration:
cannot import name getUsernameFromSiteDB
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2020-05-12 10:40:34.608 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2004/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2004/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2004/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2004/lib/CRABClient/Commands/SubCommand.py", line 318, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2004/lib/CRABClient/Commands/SubCommand.py", line 88, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Error while loading CRAB configuration:
cannot import name getUsernameFromSiteDB
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
DEBUG 2020-05-12 17:50:44.056 UTC: 	 CRAB Client version: 3.3.2005
DEBUG 2020-05-12 17:50:44.056 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-05-12 17:50:44.072 UTC: 	 OpenSSl version: OpenSSL 1.0.2k-fips  26 Jan 2017 (Library: OpenSSL 1.0.2d-fips 9 Jul 2015)
DEBUG 2020-05-12 17:50:44.072 UTC: 	 Executing command: 'submit'
DEBUG 2020-05-12 17:50:44.073 UTC: 	 Found CRAB cache file /lustre/home/venditti/.crab3
INFO 2020-05-12 17:50:44.075 UTC: 	 Will use CRAB configuration file crab_T3Mu_BPH3_RunA_cfg.py
DEBUG 2020-05-12 17:50:44.075 UTC: 	 Loading CRAB configuration file.
DEBUG 2020-05-12 17:50:44.079 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2020-05-12 17:50:44.080 UTC: 	 Working area '/lustrehome/venditti/Tau3Mu_MiniAOD/CMSSW_10_2_1/src/CrabSubmission/Data/BParking_RunD_Mini/crab_projects/crab_SkimTau3Mu_BParking_Run2018D_BPH3_Mini_v5' already exists 
Please change the requestName in the config file
ERROR 2020-05-12 17:50:44.080 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2005/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2005/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2005/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2005/lib/CRABClient/Commands/SubCommand.py", line 323, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2005/lib/CRABClient/ClientUtilities.py", line 407, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/lustrehome/venditti/Tau3Mu_MiniAOD/CMSSW_10_2_1/src/CrabSubmission/Data/BParking_RunD_Mini/crab_projects/crab_SkimTau3Mu_BParking_Run2018D_BPH3_Mini_v5' already exists 
Please change the requestName in the config file
INFO 2020-05-12 17:50:44.085 UTC: 	 Log file is /lustrehome/venditti/Tau3Mu_MiniAOD/CMSSW_10_2_1/src/CrabSubmission/Data/BParking_RunD_Mini/crab.log
