DEBUG 2019-11-27 15:18:06.906 UTC: 	 Running on: Linux ui03.recas.ba.infn.it 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2019-11-27 15:18:06.927 UTC: 	 OpenSSl version: OpenSSL 1.0.2k-fips  26 Jan 2017 (Library: OpenSSL 1.0.2d-fips 9 Jul 2015)
DEBUG 2019-11-27 15:18:06.928 UTC: 	 Executing command: 'status'
DEBUG 2019-11-27 15:18:06.928 UTC: 	 Found CRAB cache file /lustre/home/venditti/.crab3
ERROR 2019-11-27 15:18:06.930 UTC: 	 Error: crab_projects/crab_SkimTau3Mu_BParking_Run2018D_BP1/ is not a valid CRAB project directory.
ERROR 2019-11-27 15:18:06.930 UTC: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/bin/crab", line 145, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 40, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 277, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 595, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_projects/crab_SkimTau3Mu_BParking_Run2018D_BP1/ is not a valid CRAB project directory.
DEBUG 2019-11-27 15:23:17.155 UTC: 	 Running on: Linux ui03.recas.ba.infn.it 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2019-11-27 15:23:17.178 UTC: 	 OpenSSl version: OpenSSL 1.0.2k-fips  26 Jan 2017 (Library: OpenSSL 1.0.2d-fips 9 Jul 2015)
DEBUG 2019-11-27 15:23:17.178 UTC: 	 Executing command: 'status'
DEBUG 2019-11-27 15:23:17.179 UTC: 	 Found CRAB cache file /lustre/home/venditti/.crab3
ERROR 2019-11-27 15:23:17.180 UTC: 	 Error: crab_projects/crab_SkimTau3Mu_BParking_Run2018D_BP2/ is not a valid CRAB project directory.
ERROR 2019-11-27 15:23:17.180 UTC: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/bin/crab", line 145, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 40, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 277, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 595, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_projects/crab_SkimTau3Mu_BParking_Run2018D_BP2/ is not a valid CRAB project directory.
DEBUG 2019-11-28 09:35:59.527 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2019-11-28 09:35:59.542 UTC: 	 OpenSSl version: OpenSSL 1.0.2k-fips  26 Jan 2017 (Library: OpenSSL 1.0.2d-fips 9 Jul 2015)
DEBUG 2019-11-28 09:35:59.542 UTC: 	 Executing command: 'report'
DEBUG 2019-11-28 09:35:59.543 UTC: 	 Found CRAB cache file /lustre/home/venditti/.crab3
ERROR 2019-11-28 09:35:59.544 UTC: 	 Error: crab_projects/crab_SkimTau3Mu_BParking_Run2018D_BPH4_v1/Ã¹ is not a valid CRAB project directory.
ERROR 2019-11-28 09:35:59.544 UTC: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/bin/crab", line 145, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/lib/python2.7/site-packages/CRABClient/Commands/report.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 277, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 595, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_projects/crab_SkimTau3Mu_BParking_Run2018D_BPH4_v1/Ã¹ is not a valid CRAB project directory.
DEBUG 2019-11-28 09:36:02.818 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2019-11-28 09:36:02.837 UTC: 	 OpenSSl version: OpenSSL 1.0.2k-fips  26 Jan 2017 (Library: OpenSSL 1.0.2d-fips 9 Jul 2015)
DEBUG 2019-11-28 09:36:02.838 UTC: 	 Executing command: 'report'
DEBUG 2019-11-28 09:36:02.838 UTC: 	 Found CRAB cache file /lustre/home/venditti/.crab3
ERROR 2019-11-28 09:36:02.839 UTC: 	 Error: crab_projects/crab_SkimTau3Mu_BParking_Run2018D_BPH4_v1/Ã is not a valid CRAB project directory.
ERROR 2019-11-28 09:36:02.840 UTC: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/bin/crab", line 145, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/lib/python2.7/site-packages/CRABClient/Commands/report.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 277, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 595, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_projects/crab_SkimTau3Mu_BParking_Run2018D_BPH4_v1/Ã is not a valid CRAB project directory.
DEBUG 2019-11-28 17:33:47.910 UTC: 	 Running on: Linux ui03.recas.ba.infn.it 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2019-11-28 17:33:47.933 UTC: 	 OpenSSl version: OpenSSL 1.0.2k-fips  26 Jan 2017 (Library: OpenSSL 1.0.2d-fips 9 Jul 2015)
DEBUG 2019-11-28 17:33:47.934 UTC: 	 Executing command: 'submit'
DEBUG 2019-11-28 17:33:47.936 UTC: 	 Found CRAB cache file /lustre/home/venditti/.crab3
DEBUG 2019-11-28 17:33:47.947 UTC: 	 Checking credentials
DEBUG 2019-11-28 17:33:47.947 UTC: 	 Found proxy file /tmp/x509up_u50797
DEBUG 2019-11-28 17:33:47.947 UTC: 	 Getting proxy life time left
DEBUG 2019-11-28 17:33:48.753 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50797 -timeleft
 output : 40998

 error: 
 retcode : 0
DEBUG 2019-11-28 17:33:49.559 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50797 -actimeleft
 output : 40997

 error: 
 retcode : 0
DEBUG 2019-11-28 17:33:49.559 UTC: 	 Proxy lifetime 40998 secs is different from voms extension lifetime 40997 secs for proxy: /tmp/x509up_u50797
DEBUG 2019-11-28 17:33:49.559 UTC: 	 Proxy valid for 11:23:17 hours
INFO 2019-11-28 17:33:49.559 UTC: 	 Will use CRAB configuration file crab_T3Mu_BPH4_RunA_cfg.py
DEBUG 2019-11-28 17:33:49.560 UTC: 	 Loading CRAB configuration file.
DEBUG 2019-11-28 17:33:52.435 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2019-11-28 17:33:52.437 UTC: 	 Working area '/lustrehome/venditti/Tau3Mu2018_final/CMSSW_10_6_1/src/CrabSubmission/Data/BParking_RunD/crab_projects/crab_SkimTau3Mu_BParking_Run2018D_BPH4_v1' already exists 
Please change the requestName in the config file
ERROR 2019-11-28 17:33:52.438 UTC: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/bin/crab", line 145, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 324, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 413, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/lustrehome/venditti/Tau3Mu2018_final/CMSSW_10_6_1/src/CrabSubmission/Data/BParking_RunD/crab_projects/crab_SkimTau3Mu_BParking_Run2018D_BPH4_v1' already exists 
Please change the requestName in the config file
DEBUG 2019-11-28 17:38:11.066 UTC: 	 Running on: Linux ui03.recas.ba.infn.it 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2019-11-28 17:38:11.087 UTC: 	 OpenSSl version: OpenSSL 1.0.2k-fips  26 Jan 2017 (Library: OpenSSL 1.0.2d-fips 9 Jul 2015)
DEBUG 2019-11-28 17:38:11.088 UTC: 	 Executing command: 'submit'
DEBUG 2019-11-28 17:38:11.088 UTC: 	 Found CRAB cache file /lustre/home/venditti/.crab3
DEBUG 2019-11-28 17:38:11.098 UTC: 	 Checking credentials
DEBUG 2019-11-28 17:38:11.099 UTC: 	 Found proxy file /tmp/x509up_u50797
DEBUG 2019-11-28 17:38:11.099 UTC: 	 Getting proxy life time left
DEBUG 2019-11-28 17:38:11.904 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50797 -timeleft
 output : 40735

 error: 
 retcode : 0
DEBUG 2019-11-28 17:38:12.610 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50797 -actimeleft
 output : 40734

 error: 
 retcode : 0
DEBUG 2019-11-28 17:38:12.611 UTC: 	 Proxy lifetime 40735 secs is different from voms extension lifetime 40734 secs for proxy: /tmp/x509up_u50797
DEBUG 2019-11-28 17:38:12.611 UTC: 	 Proxy valid for 11:18:54 hours
ERROR 2019-11-28 17:38:12.611 UTC: 	 CRAB configuration file crab_T3Mu_BPH1_RunD_cfg.py not found.
ERROR 2019-11-28 17:38:12.612 UTC: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/bin/crab", line 145, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 320, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 50, in loadConfig
    raise ConfigurationException("CRAB configuration file %s not found." % (configname))
ConfigurationException: CRAB configuration file crab_T3Mu_BPH1_RunD_cfg.py not found.
DEBUG 2019-11-28 17:38:18.050 UTC: 	 Running on: Linux ui03.recas.ba.infn.it 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2019-11-28 17:38:18.071 UTC: 	 OpenSSl version: OpenSSL 1.0.2k-fips  26 Jan 2017 (Library: OpenSSL 1.0.2d-fips 9 Jul 2015)
DEBUG 2019-11-28 17:38:18.071 UTC: 	 Executing command: 'submit'
DEBUG 2019-11-28 17:38:18.071 UTC: 	 Found CRAB cache file /lustre/home/venditti/.crab3
DEBUG 2019-11-28 17:38:18.079 UTC: 	 Checking credentials
DEBUG 2019-11-28 17:38:18.079 UTC: 	 Found proxy file /tmp/x509up_u50797
DEBUG 2019-11-28 17:38:18.079 UTC: 	 Getting proxy life time left
DEBUG 2019-11-28 17:38:18.884 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50797 -timeleft
 output : 40728

 error: 
 retcode : 0
DEBUG 2019-11-28 17:38:19.590 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50797 -actimeleft
 output : 40727

 error: 
 retcode : 0
DEBUG 2019-11-28 17:38:19.591 UTC: 	 Proxy lifetime 40728 secs is different from voms extension lifetime 40727 secs for proxy: /tmp/x509up_u50797
DEBUG 2019-11-28 17:38:19.591 UTC: 	 Proxy valid for 11:18:47 hours
ERROR 2019-11-28 17:38:19.591 UTC: 	 CRAB configuration file crab_T3Mu_BPH2_RunD_cfg.py not found.
ERROR 2019-11-28 17:38:19.591 UTC: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/bin/crab", line 145, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 320, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 50, in loadConfig
    raise ConfigurationException("CRAB configuration file %s not found." % (configname))
ConfigurationException: CRAB configuration file crab_T3Mu_BPH2_RunD_cfg.py not found.
DEBUG 2019-11-28 17:38:51.196 UTC: 	 Running on: Linux ui03.recas.ba.infn.it 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2019-11-28 17:38:51.216 UTC: 	 OpenSSl version: OpenSSL 1.0.2k-fips  26 Jan 2017 (Library: OpenSSL 1.0.2d-fips 9 Jul 2015)
DEBUG 2019-11-28 17:38:51.217 UTC: 	 Executing command: 'submit'
DEBUG 2019-11-28 17:38:51.217 UTC: 	 Found CRAB cache file /lustre/home/venditti/.crab3
DEBUG 2019-11-28 17:38:51.225 UTC: 	 Checking credentials
DEBUG 2019-11-28 17:38:51.225 UTC: 	 Found proxy file /tmp/x509up_u50797
DEBUG 2019-11-28 17:38:51.225 UTC: 	 Getting proxy life time left
DEBUG 2019-11-28 17:38:52.030 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50797 -timeleft
 output : 40695

 error: 
 retcode : 0
DEBUG 2019-11-28 17:38:52.737 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50797 -actimeleft
 output : 40694

 error: 
 retcode : 0
DEBUG 2019-11-28 17:38:52.737 UTC: 	 Proxy lifetime 40695 secs is different from voms extension lifetime 40694 secs for proxy: /tmp/x509up_u50797
DEBUG 2019-11-28 17:38:52.737 UTC: 	 Proxy valid for 11:18:14 hours
INFO 2019-11-28 17:38:52.737 UTC: 	 Will use CRAB configuration file crab_T3Mu_BPH1_RunA_cfg.py
DEBUG 2019-11-28 17:38:52.737 UTC: 	 Loading CRAB configuration file.
DEBUG 2019-11-28 17:38:55.635 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2019-11-28 17:38:55.636 UTC: 	 Working area '/lustrehome/venditti/Tau3Mu2018_final/CMSSW_10_6_1/src/CrabSubmission/Data/BParking_RunD/crab_projects/crab_SkimTau3Mu_BParking_Run2018D_BPH1' already exists 
Please change the requestName in the config file
ERROR 2019-11-28 17:38:55.636 UTC: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/bin/crab", line 145, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 324, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 413, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/lustrehome/venditti/Tau3Mu2018_final/CMSSW_10_6_1/src/CrabSubmission/Data/BParking_RunD/crab_projects/crab_SkimTau3Mu_BParking_Run2018D_BPH1' already exists 
Please change the requestName in the config file
DEBUG 2019-12-03 14:26:46.494 UTC: 	 Running on: Linux ui03.recas.ba.infn.it 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2019-12-03 14:26:46.516 UTC: 	 OpenSSl version: OpenSSL 1.0.2k-fips  26 Jan 2017 (Library: OpenSSL 1.0.2d-fips 9 Jul 2015)
DEBUG 2019-12-03 14:26:46.516 UTC: 	 Executing command: 'submit'
DEBUG 2019-12-03 14:26:46.517 UTC: 	 Found CRAB cache file /lustre/home/venditti/.crab3
DEBUG 2019-12-03 14:26:46.525 UTC: 	 Checking credentials
DEBUG 2019-12-03 14:26:46.526 UTC: 	 Found proxy file /tmp/x509up_u50797
DEBUG 2019-12-03 14:26:46.526 UTC: 	 Getting proxy life time left
DEBUG 2019-12-03 14:26:47.235 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50797 -timeleft
 output : 41021

 error: 
 retcode : 0
DEBUG 2019-12-03 14:26:47.941 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50797 -actimeleft
 output : 41021

 error: 
 retcode : 0
DEBUG 2019-12-03 14:26:47.941 UTC: 	 Proxy valid for 11:23:41 hours
INFO 2019-12-03 14:26:47.941 UTC: 	 Will use CRAB configuration file crab_T3Mu_BPH2_RunA_cfg.py
DEBUG 2019-12-03 14:26:47.941 UTC: 	 Loading CRAB configuration file.
DEBUG 2019-12-03 14:26:50.849 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2019-12-03 14:26:50.851 UTC: 	 Working area '/lustrehome/venditti/Tau3Mu2018_final/CMSSW_10_6_1/src/CrabSubmission/Data/SkimDsPhiPi/BParking_RunD/crab_projects/crab_SkimDsPhiPi_BParking_Run2018D_BPH2_v3' already exists 
Please change the requestName in the config file
ERROR 2019-12-03 14:26:50.852 UTC: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/bin/crab", line 145, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 324, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 413, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/lustrehome/venditti/Tau3Mu2018_final/CMSSW_10_6_1/src/CrabSubmission/Data/SkimDsPhiPi/BParking_RunD/crab_projects/crab_SkimDsPhiPi_BParking_Run2018D_BPH2_v3' already exists 
Please change the requestName in the config file
DEBUG 2019-12-03 14:26:56.299 UTC: 	 Running on: Linux ui03.recas.ba.infn.it 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2019-12-03 14:26:56.318 UTC: 	 OpenSSl version: OpenSSL 1.0.2k-fips  26 Jan 2017 (Library: OpenSSL 1.0.2d-fips 9 Jul 2015)
DEBUG 2019-12-03 14:26:56.319 UTC: 	 Executing command: 'submit'
DEBUG 2019-12-03 14:26:56.319 UTC: 	 Found CRAB cache file /lustre/home/venditti/.crab3
DEBUG 2019-12-03 14:26:56.326 UTC: 	 Checking credentials
DEBUG 2019-12-03 14:26:56.326 UTC: 	 Found proxy file /tmp/x509up_u50797
DEBUG 2019-12-03 14:26:56.326 UTC: 	 Getting proxy life time left
DEBUG 2019-12-03 14:26:57.131 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50797 -timeleft
 output : 41011

 error: 
 retcode : 0
DEBUG 2019-12-03 14:26:57.937 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50797 -actimeleft
 output : 41011

 error: 
 retcode : 0
DEBUG 2019-12-03 14:26:57.938 UTC: 	 Proxy valid for 11:23:31 hours
INFO 2019-12-03 14:26:57.938 UTC: 	 Will use CRAB configuration file crab_T3Mu_BPH3_RunA_cfg.py
DEBUG 2019-12-03 14:26:57.938 UTC: 	 Loading CRAB configuration file.
DEBUG 2019-12-03 14:27:00.826 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2019-12-03 14:27:00.827 UTC: 	 Working area '/lustrehome/venditti/Tau3Mu2018_final/CMSSW_10_6_1/src/CrabSubmission/Data/SkimDsPhiPi/BParking_RunD/crab_projects/crab_SkimDsPhiPi_BParking_Run2018D_BPH3_v3' already exists 
Please change the requestName in the config file
ERROR 2019-12-03 14:27:00.827 UTC: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/bin/crab", line 145, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 324, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 413, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/lustrehome/venditti/Tau3Mu2018_final/CMSSW_10_6_1/src/CrabSubmission/Data/SkimDsPhiPi/BParking_RunD/crab_projects/crab_SkimDsPhiPi_BParking_Run2018D_BPH3_v3' already exists 
Please change the requestName in the config file
DEBUG 2019-12-03 14:27:06.222 UTC: 	 Running on: Linux ui03.recas.ba.infn.it 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2019-12-03 14:27:06.238 UTC: 	 OpenSSl version: OpenSSL 1.0.2k-fips  26 Jan 2017 (Library: OpenSSL 1.0.2d-fips 9 Jul 2015)
DEBUG 2019-12-03 14:27:06.238 UTC: 	 Executing command: 'submit'
DEBUG 2019-12-03 14:27:06.238 UTC: 	 Found CRAB cache file /lustre/home/venditti/.crab3
DEBUG 2019-12-03 14:27:06.244 UTC: 	 Checking credentials
DEBUG 2019-12-03 14:27:06.244 UTC: 	 Found proxy file /tmp/x509up_u50797
DEBUG 2019-12-03 14:27:06.244 UTC: 	 Getting proxy life time left
DEBUG 2019-12-03 14:27:06.949 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50797 -timeleft
 output : 41002

 error: 
 retcode : 0
DEBUG 2019-12-03 14:27:07.655 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50797 -actimeleft
 output : 41001

 error: 
 retcode : 0
DEBUG 2019-12-03 14:27:07.655 UTC: 	 Proxy lifetime 41002 secs is different from voms extension lifetime 41001 secs for proxy: /tmp/x509up_u50797
DEBUG 2019-12-03 14:27:07.655 UTC: 	 Proxy valid for 11:23:21 hours
INFO 2019-12-03 14:27:07.655 UTC: 	 Will use CRAB configuration file crab_T3Mu_BPH4_RunA_cfg.py
DEBUG 2019-12-03 14:27:07.656 UTC: 	 Loading CRAB configuration file.
DEBUG 2019-12-03 14:27:10.538 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2019-12-03 14:27:10.539 UTC: 	 Working area '/lustrehome/venditti/Tau3Mu2018_final/CMSSW_10_6_1/src/CrabSubmission/Data/SkimDsPhiPi/BParking_RunD/crab_projects/crab_SkimDsPhiPi_BParking_Run2018D_BPH4_v3' already exists 
Please change the requestName in the config file
ERROR 2019-12-03 14:27:10.539 UTC: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/bin/crab", line 145, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 324, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 413, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/lustrehome/venditti/Tau3Mu2018_final/CMSSW_10_6_1/src/CrabSubmission/Data/SkimDsPhiPi/BParking_RunD/crab_projects/crab_SkimDsPhiPi_BParking_Run2018D_BPH4_v3' already exists 
Please change the requestName in the config file
DEBUG 2019-12-03 14:27:15.996 UTC: 	 Running on: Linux ui03.recas.ba.infn.it 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2019-12-03 14:27:16.013 UTC: 	 OpenSSl version: OpenSSL 1.0.2k-fips  26 Jan 2017 (Library: OpenSSL 1.0.2d-fips 9 Jul 2015)
DEBUG 2019-12-03 14:27:16.013 UTC: 	 Executing command: 'submit'
DEBUG 2019-12-03 14:27:16.013 UTC: 	 Found CRAB cache file /lustre/home/venditti/.crab3
DEBUG 2019-12-03 14:27:16.021 UTC: 	 Checking credentials
DEBUG 2019-12-03 14:27:16.021 UTC: 	 Found proxy file /tmp/x509up_u50797
DEBUG 2019-12-03 14:27:16.021 UTC: 	 Getting proxy life time left
DEBUG 2019-12-03 14:27:16.726 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50797 -timeleft
 output : 40992

 error: 
 retcode : 0
DEBUG 2019-12-03 14:27:17.431 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50797 -actimeleft
 output : 40991

 error: 
 retcode : 0
DEBUG 2019-12-03 14:27:17.431 UTC: 	 Proxy lifetime 40992 secs is different from voms extension lifetime 40991 secs for proxy: /tmp/x509up_u50797
DEBUG 2019-12-03 14:27:17.431 UTC: 	 Proxy valid for 11:23:11 hours
INFO 2019-12-03 14:27:17.431 UTC: 	 Will use CRAB configuration file crab_T3Mu_BPH5_RunA_cfg.py
DEBUG 2019-12-03 14:27:17.432 UTC: 	 Loading CRAB configuration file.
DEBUG 2019-12-03 14:27:20.388 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2019-12-03 14:27:20.389 UTC: 	 Working area '/lustrehome/venditti/Tau3Mu2018_final/CMSSW_10_6_1/src/CrabSubmission/Data/SkimDsPhiPi/BParking_RunD/crab_projects/crab_SkimDsPhiPi_BParking_Run2018D_BPH5_v3' already exists 
Please change the requestName in the config file
ERROR 2019-12-03 14:27:20.389 UTC: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/bin/crab", line 145, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 324, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 413, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/lustrehome/venditti/Tau3Mu2018_final/CMSSW_10_6_1/src/CrabSubmission/Data/SkimDsPhiPi/BParking_RunD/crab_projects/crab_SkimDsPhiPi_BParking_Run2018D_BPH5_v3' already exists 
Please change the requestName in the config file
DEBUG 2019-12-23 10:20:06.058 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2019-12-23 10:20:06.071 UTC: 	 OpenSSl version: OpenSSL 1.0.2k-fips  26 Jan 2017 (Library: OpenSSL 1.0.2d-fips 9 Jul 2015)
DEBUG 2019-12-23 10:20:06.071 UTC: 	 Executing command: 'submit'
DEBUG 2019-12-23 10:20:06.126 UTC: 	 Found CRAB cache file /lustre/home/venditti/.crab3
DEBUG 2019-12-23 10:20:06.136 UTC: 	 Checking credentials
DEBUG 2019-12-23 10:20:06.136 UTC: 	 Found proxy file /tmp/x509up_u50797
DEBUG 2019-12-23 10:20:06.136 UTC: 	 Getting proxy life time left
DEBUG 2019-12-23 10:20:06.841 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50797 -timeleft
 output : 42866

 error: 
 retcode : 0
DEBUG 2019-12-23 10:20:07.546 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50797 -actimeleft
 output : 42864

 error: 
 retcode : 0
DEBUG 2019-12-23 10:20:07.546 UTC: 	 Proxy lifetime 42866 secs is different from voms extension lifetime 42864 secs for proxy: /tmp/x509up_u50797
DEBUG 2019-12-23 10:20:07.546 UTC: 	 Proxy valid for 11:54:24 hours
INFO 2019-12-23 10:20:07.547 UTC: 	 Will use CRAB configuration file crab_T3Mu_BPH1_RunA_cfg.py
DEBUG 2019-12-23 10:20:07.547 UTC: 	 Loading CRAB configuration file.
DEBUG 2019-12-23 10:20:10.223 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2019-12-23 10:20:10.223 UTC: 	 Invalid CRAB configuration: Parameter Data.inputDBS has an invalid value (' global').
Allowed values are: 'global' ('https://cmsweb.cern.ch/dbs/prod/global/DBSReader')
                    'phys02' ('https://cmsweb.cern.ch/dbs/prod/phys02/DBSReader')
                    'phys03' ('https://cmsweb.cern.ch/dbs/prod/phys03/DBSReader')
                    'phys01' ('https://cmsweb.cern.ch/dbs/prod/phys01/DBSReader')
If Data.inputDBS would not be specified, the default 'global' ('https://cmsweb.cern.ch/dbs/prod/global/DBSReader') would be used.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2019-12-23 10:20:10.224 UTC: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/bin/crab", line 145, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 320, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1911.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 93, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Invalid CRAB configuration: Parameter Data.inputDBS has an invalid value (' global').
Allowed values are: 'global' ('https://cmsweb.cern.ch/dbs/prod/global/DBSReader')
                    'phys02' ('https://cmsweb.cern.ch/dbs/prod/phys02/DBSReader')
                    'phys03' ('https://cmsweb.cern.ch/dbs/prod/phys03/DBSReader')
                    'phys01' ('https://cmsweb.cern.ch/dbs/prod/phys01/DBSReader')
If Data.inputDBS would not be specified, the default 'global' ('https://cmsweb.cern.ch/dbs/prod/global/DBSReader') would be used.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
DEBUG 2020-02-09 17:59:00.569 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-02-09 17:59:00.579 UTC: 	 OpenSSl version: OpenSSL 1.0.2k-fips  26 Jan 2017 (Library: OpenSSL 1.0.2d-fips 9 Jul 2015)
DEBUG 2020-02-09 17:59:00.580 UTC: 	 Executing command: 'submit'
DEBUG 2020-02-09 17:59:00.581 UTC: 	 Found CRAB cache file /lustre/home/venditti/.crab3
DEBUG 2020-02-09 17:59:00.586 UTC: 	 Checking credentials
DEBUG 2020-02-09 17:59:00.586 UTC: 	 Found proxy file /tmp/x509up_u50797
DEBUG 2020-02-09 17:59:00.586 UTC: 	 Getting proxy life time left
DEBUG 2020-02-09 17:59:01.189 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50797 -timeleft
 output : 42722

 error: 
 retcode : 0
DEBUG 2020-02-09 17:59:01.793 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50797 -actimeleft
 output : 42722

 error: 
 retcode : 0
DEBUG 2020-02-09 17:59:01.793 UTC: 	 Proxy valid for 11:52:02 hours
INFO 2020-02-09 17:59:01.794 UTC: 	 Will use CRAB configuration file crab_T3Mu_BPH5_RunA_cfg.py
DEBUG 2020-02-09 17:59:01.794 UTC: 	 Loading CRAB configuration file.
ERROR 2020-02-09 17:59:04.376 UTC: 	 The 'dryrun' option is not compatible with the 'Automatic' splitting mode (default).
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2020-02-09 17:59:04.377 UTC: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/bin/crab", line 145, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 320, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 93, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: The 'dryrun' option is not compatible with the 'Automatic' splitting mode (default).
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
DEBUG 2020-02-18 17:32:30.706 UTC: 	 Running on: Linux ui03.recas.ba.infn.it 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-02-18 17:32:30.753 UTC: 	 OpenSSl version: OpenSSL 1.0.2k-fips  26 Jan 2017 (Library: OpenSSL 1.0.2d-fips 9 Jul 2015)
DEBUG 2020-02-18 17:32:30.754 UTC: 	 Executing command: 'status'
DEBUG 2020-02-18 17:32:30.754 UTC: 	 Found CRAB cache file /lustre/home/venditti/.crab3
ERROR 2020-02-18 17:32:30.755 UTC: 	 Cannot find .requestcache file in CRAB project directory /lustrehome/venditti/Tau3Mu2018_final/CMSSW_10_6_1/src/CrabSubmission/Data/SkimDsPhiPi/BParking_RunD/crab_projects
ERROR 2020-02-18 17:32:30.756 UTC: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/bin/crab", line 145, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 40, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 277, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 599, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 461, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /lustrehome/venditti/Tau3Mu2018_final/CMSSW_10_6_1/src/CrabSubmission/Data/SkimDsPhiPi/BParking_RunD/crab_projects
